Add config option for imgui font
TASLabz/dolphin pull request #42
Opened 2023-04-15 19:24 UTC by Hibyehello

Font size only applies to custom fonts not Default

2023-04-22 20:33 UTC, ximk approved these changes
Approving from a testing and compiling standpoint. **Do not merge until a thorough code review is done.**

2023-04-22 22:00 UTC, malleoz requested changes

2023-04-22 22:00 UTC, malleoz commented on Source/Core/VideoCommon/OnScreenUI.cpp
> +    if(Config::Get(Config::MAIN_IMGUI_FONT) != "Default"){
Your indentation is messed up here.

2023-04-23 03:07 UTC, vabold requested changes

2023-04-23 03:07 UTC, vabold commented on Source/Core/Core/API/Gui.h
> +static ImFont* font;
`g_font`.

2023-04-28 00:21 UTC, Hibyehello commented on Source/Core/Core/API/Gui.cpp
> +	GUI_DRAW_DEFERRED(AddText(API::font, Config::Get(Config::MAIN_IMGUI_FONT_SIZE), ImVec2(pos.x+1, pos.y+1), ARGBToABGR(color^0x00FFFFFF), text.c_str()));
I'm not sure what'd be the best way

2023-05-09 14:34 UTC, ximk reviewed
I just have optional things to consider including/changing, nothing major.

2023-05-10 03:32 UTC, malleoz requested changes

2023-05-10 03:32 UTC, malleoz commented on Source/Core/Core/API/Gui.cpp
> +	GUI_DRAW_DEFERRED(AddText(API::g_font, Config::Get(Config::MAIN_IMGUI_FONT_SIZE), ImVec2(pos.x+1, pos.y+1), ARGBToABGR(color^0x00FFFFFF), text.c_str()));
Your indentation is messed up here.

2023-05-10 14:16 UTC, Hibyehello commented
@malleoz I think I've addressed everything you wanted addressed

2023-06-08 23:07 UTC, malleoz approved these changes

2023-06-08 23:08 UTC, merged