Scripting: Add read_bytes to memory module
TASLabz/dolphin pull request #81
Opened 2023-09-22 19:40 UTC by malleoz

This adds a new function to the memory module, accessible by Python via `memory.read_bytes(addr, size)`.

I found that it was annoying to read arbitrary number of bytes, such as pulling the Mii data struct byte-by-byte. Instead, this function will allow the user to query Dolphin for a certain number of bytes, and it will return a Python `bytearray`. I went with this as opposed to a `bytes` object, as I think `bytearray` allows for more easy manipulation of the data contained within.

Note that `MMU::ReadFromHardware` contains a translation check to prevent reads from invalid memory. The result is that it will return 0x00 for that byte. **We could debate whether to only return a bytearray with length equal to the number of bytes read successfully, or keep the current behavior that invalid accesses will just return 0x00.**

NOTE: `chase_pointer()` should be updated to support this module.

2023-09-23 00:54 UTC, malleoz commented
Forgot to update the python stub.

2023-09-25 06:21 UTC, malleoz commented
Updated to include `write_bytes`

2023-09-26 12:05 UTC, ximk requested changes

2023-09-26 12:05 UTC, ximk commented on python-stubs/dolphin_memory.pyi
Forgot to add a `write_bytes` stub here. :)

2023-09-27 00:27 UTC, ximk requested changes

2023-09-27 00:27 UTC, ximk commented on python-stubs/dolphin_memory.pyi
> +    :param byrtes: bytearray of bytes to write
```suggestion
    :param bytes: bytearray of bytes to write
```

2023-09-27 00:30 UTC, ximk approved these changes

2023-09-27 00:32 UTC, merged